// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminTeamsSettingsInfoSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminTeamsSettingsInfoRequest struct {
	TeamID string `queryParam:"style=form,explode=true,name=team_id"`
	// Authentication token. Requires scope: `admin.teams:read`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminTeamsSettingsInfoResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
