// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminEmojiAddSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminEmojiAddRequestBody struct {
	// The name of the emoji to be removed. Colons (`:myemoji:`) around the value are not required, although they may be included.
	Name string `form:"name=name"`
	// Authentication token. Requires scope: `admin.teams:write`
	Token string `form:"name=token"`
	// The URL of a file to use as an image for the emoji. Square images under 128KB and with transparent backgrounds work best.
	URL string `form:"name=url"`
}

type AdminEmojiAddResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
