// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminTeamsSettingsSetDiscoverabilitySecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminTeamsSettingsSetDiscoverabilityApplicationJSON struct {
	// This workspace's discovery setting. It must be set to one of `open`, `invite_only`, `closed`, or `unlisted`.
	Discoverability string `json:"discoverability"`
	// The ID of the workspace to set discoverability on.
	TeamID string `json:"team_id"`
}

type AdminTeamsSettingsSetDiscoverabilityRequest struct {
	RequestBody AdminTeamsSettingsSetDiscoverabilityApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `admin.teams:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminTeamsSettingsSetDiscoverabilityResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
