// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminUsersSessionResetSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminUsersSessionResetApplicationJSON struct {
	// Only expire mobile sessions (default: false)
	MobileOnly *bool `json:"mobile_only,omitempty"`
	// The ID of the user to wipe sessions for
	UserID string `json:"user_id"`
	// Only expire web sessions (default: false)
	WebOnly *bool `json:"web_only,omitempty"`
}

type AdminUsersSessionResetRequest struct {
	RequestBody AdminUsersSessionResetApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `admin.users:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminUsersSessionResetResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
