// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminTeamsOwnersListSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminTeamsOwnersListRequest struct {
	// Set `cursor` to `next_cursor` returned by the previous call to list items in the next page.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// The maximum number of items to return. Must be between 1 - 1000 both inclusive.
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	TeamID string `queryParam:"style=form,explode=true,name=team_id"`
	// Authentication token. Requires scope: `admin.teams:read`
	Token string `queryParam:"style=form,explode=true,name=token"`
}

type AdminTeamsOwnersListResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
