// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminInviteRequestsDenySecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminInviteRequestsDenyApplicationJSON struct {
	// ID of the request to invite.
	InviteRequestID string `json:"invite_request_id"`
	// ID for the workspace where the invite request was made.
	TeamID *string `json:"team_id,omitempty"`
}

type AdminInviteRequestsDenyRequest struct {
	RequestBody AdminInviteRequestsDenyApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `admin.invites:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminInviteRequestsDenyResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
