// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminConversationsRestrictAccessListGroupsSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminConversationsRestrictAccessListGroupsRequest struct {
	ChannelID string `queryParam:"style=form,explode=true,name=channel_id"`
	// The workspace where the channel exists. This argument is required for channels only tied to one workspace, and optional for channels that are shared across an organization.
	TeamID *string `queryParam:"style=form,explode=true,name=team_id"`
	// Authentication token. Requires scope: `admin.conversations:read`
	Token string `queryParam:"style=form,explode=true,name=token"`
}

type AdminConversationsRestrictAccessListGroupsResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
