// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminConversationsRestrictAccessAddGroupSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminConversationsRestrictAccessAddGroupRequestBody struct {
	// The channel to link this group to.
	ChannelID string `form:"name=channel_id"`
	// The [IDP Group](https://slack.com/help/articles/115001435788-Connect-identity-provider-groups-to-your-Enterprise-Grid-org) ID to be an allowlist for the private channel.
	GroupID string `form:"name=group_id"`
	// The workspace where the channel exists. This argument is required for channels only tied to one workspace, and optional for channels that are shared across an organization.
	TeamID *string `form:"name=team_id"`
	// Authentication token. Requires scope: `admin.conversations:write`
	Token string `form:"name=token"`
}

type AdminConversationsRestrictAccessAddGroupResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
