// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminUsersSessionInvalidateSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminUsersSessionInvalidateApplicationJSON struct {
	SessionID int `json:"session_id"`
	// ID of the team that the session belongs to
	TeamID string `json:"team_id"`
}

type AdminUsersSessionInvalidateRequest struct {
	RequestBody AdminUsersSessionInvalidateApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `admin.users:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminUsersSessionInvalidateResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
