// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminTeamsSettingsSetNameSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminTeamsSettingsSetNameApplicationJSON struct {
	// The new name of the workspace.
	Name string `json:"name"`
	// ID for the workspace to set the name for.
	TeamID string `json:"team_id"`
}

type AdminTeamsSettingsSetNameRequest struct {
	RequestBody AdminTeamsSettingsSetNameApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `admin.teams:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminTeamsSettingsSetNameResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
