// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminTeamsSettingsSetDefaultChannelsSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminTeamsSettingsSetDefaultChannelsRequestBody struct {
	// An array of channel IDs.
	ChannelIds string `form:"name=channel_ids"`
	// ID for the workspace to set the default channel for.
	TeamID string `form:"name=team_id"`
	// Authentication token. Requires scope: `admin.teams:write`
	Token string `form:"name=token"`
}

type AdminTeamsSettingsSetDefaultChannelsResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
