// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminUsergroupsListChannelsSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminUsergroupsListChannelsRequest struct {
	// Flag to include or exclude the count of members per channel.
	IncludeNumMembers *bool `queryParam:"style=form,explode=true,name=include_num_members"`
	// ID of the the workspace.
	TeamID *string `queryParam:"style=form,explode=true,name=team_id"`
	// Authentication token. Requires scope: `admin.usergroups:read`
	Token string `header:"style=simple,explode=false,name=token"`
	// ID of the IDP group to list default channels for.
	UsergroupID string `queryParam:"style=form,explode=true,name=usergroup_id"`
}

type AdminUsergroupsListChannelsResponse struct {
	ContentType string
	// Typical error response if the token provided is not associated with an Org Admin or Owner
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
