// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminUsersListSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminUsersListRequest struct {
	// Set `cursor` to `next_cursor` returned by the previous call to list items in the next page.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Limit for how many users to be retrieved per page
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// The ID (`T1234`) of the workspace.
	TeamID string `queryParam:"style=form,explode=true,name=team_id"`
	// Authentication token. Requires scope: `admin.users:read`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminUsersListResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
