// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminUsersSetAdminSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminUsersSetAdminApplicationJSON struct {
	// The ID (`T1234`) of the workspace.
	TeamID string `json:"team_id"`
	// The ID of the user to designate as an admin.
	UserID string `json:"user_id"`
}

type AdminUsersSetAdminRequest struct {
	RequestBody AdminUsersSetAdminApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `admin.users:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminUsersSetAdminResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
