// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminUsergroupsAddTeamsSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminUsergroupsAddTeamsApplicationJSON struct {
	// When `true`, this method automatically creates new workspace accounts for the IDP group members.
	AutoProvision *bool `json:"auto_provision,omitempty"`
	// A comma separated list of encoded team (workspace) IDs. Each workspace *MUST* belong to the organization associated with the token.
	TeamIds string `json:"team_ids"`
	// An encoded usergroup (IDP Group) ID.
	UsergroupID string `json:"usergroup_id"`
}

type AdminUsergroupsAddTeamsRequest struct {
	RequestBody AdminUsergroupsAddTeamsApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `admin.teams:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminUsergroupsAddTeamsResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
