// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminConversationsGetTeamsSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminConversationsGetTeamsRequest struct {
	// The channel to determine connected workspaces within the organization for.
	ChannelID string `queryParam:"style=form,explode=true,name=channel_id"`
	// Set `cursor` to `next_cursor` returned by the previous call to list items in the next page
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// The maximum number of items to return. Must be between 1 - 1000 both inclusive.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Authentication token. Requires scope: `admin.conversations:read`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminConversationsGetTeamsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	AdminConversationsGetTeamsErrorSchema map[string]map[string]interface{}
	// Typical success response
	AdminConversationsGetTeamsSchema map[string]map[string]interface{}
}
