// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminConversationsDisconnectSharedSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminConversationsDisconnectSharedApplicationJSON struct {
	// The channel to be disconnected from some workspaces.
	ChannelID string `json:"channel_id"`
	// The team to be removed from the channel. Currently only a single team id can be specified.
	LeavingTeamIds *string `json:"leaving_team_ids,omitempty"`
}

type AdminConversationsDisconnectSharedRequest struct {
	RequestBody AdminConversationsDisconnectSharedApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `admin.conversations:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminConversationsDisconnectSharedResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	AdminConversationsDisconnectSharedErrorSchema map[string]map[string]interface{}
	// Typical success response
	AdminConversationsRenameSchema map[string]map[string]interface{}
}
