// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminConversationsRenameSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminConversationsRenameApplicationJSON struct {
	// The channel to rename.
	ChannelID string `json:"channel_id"`
	Name      string `json:"name"`
}

type AdminConversationsRenameRequest struct {
	RequestBody AdminConversationsRenameApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `admin.conversations:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminConversationsRenameResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical success response
	AdminConversationsRenameSchema map[string]map[string]interface{}
	// Typical error response
	AdminConversationsUnarchiveErrorSchema map[string]map[string]interface{}
}
