// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminConversationsInviteSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminConversationsInviteApplicationJSON struct {
	// The channel that the users will be invited to.
	ChannelID string `json:"channel_id"`
	// The users to invite.
	UserIds string `json:"user_ids"`
}

type AdminConversationsInviteRequest struct {
	RequestBody AdminConversationsInviteApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `admin.conversations:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminConversationsInviteResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	AdminConversationsInviteErrorSchema map[string]map[string]interface{}
	// Typical success response
	AdminConversationsInviteSchema map[string]map[string]interface{}
}
