// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminAppsRestrictSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminAppsRestrictApplicationJSON struct {
	// The id of the app to restrict.
	AppID *string `json:"app_id,omitempty"`
	// The id of the request to restrict.
	RequestID *string `json:"request_id,omitempty"`
	TeamID    *string `json:"team_id,omitempty"`
}

type AdminAppsRestrictRequest struct {
	RequestBody *AdminAppsRestrictApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `admin.apps:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminAppsRestrictResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
