// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminConversationsGetConversationPrefsSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AdminConversationsGetConversationPrefsRequest struct {
	// The channel to get preferences for.
	ChannelID string `queryParam:"style=form,explode=true,name=channel_id"`
	// Authentication token. Requires scope: `admin.conversations:read`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AdminConversationsGetConversationPrefsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical success response
	AdminConversationsGetConversationPrefsSchema map[string]map[string]interface{}
	// Typical error response
	AdminConversationsUnarchiveErrorSchema map[string]map[string]interface{}
}
