// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AppsPermissionsInfoSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AppsPermissionsInfoRequest struct {
	// Authentication token. Requires scope: `none`
	Token *string `queryParam:"style=form,explode=true,name=token"`
}

type AppsPermissionsInfoResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Standard failure response when used with an invalid token
	AppsPermissionsInfoErrorSchema map[string]map[string]interface{}
	// Standard success response when used with a user token
	AppsPermissionsInfoSchema map[string]map[string]interface{}
}
