// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AppsEventAuthorizationsListSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AppsEventAuthorizationsListRequest struct {
	Cursor       *string `queryParam:"style=form,explode=true,name=cursor"`
	EventContext string  `queryParam:"style=form,explode=true,name=event_context"`
	Limit        *int64  `queryParam:"style=form,explode=true,name=limit"`
	// Authentication token. Requires scope: `authorizations:read`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AppsEventAuthorizationsListResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
