// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AppsPermissionsResourcesListSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AppsPermissionsResourcesListRequest struct {
	// Paginate through collections of data by setting the `cursor` parameter to a `next_cursor` attribute returned by a previous request's `response_metadata`. Default value fetches the first "page" of the collection. See [pagination](/docs/pagination) for more detail.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// The maximum number of items to return.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Authentication token. Requires scope: `none`
	Token string `queryParam:"style=form,explode=true,name=token"`
}

type AppsPermissionsResourcesListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	AppsPermissionsResourcesListErrorSchema map[string]map[string]interface{}
	// Typical successful paginated response
	AppsPermissionsResourcesListSuccessSchema map[string]map[string]interface{}
}
