// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AppsUninstallSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AppsUninstallRequest struct {
	// Issued when you created your application.
	ClientID *string `queryParam:"style=form,explode=true,name=client_id"`
	// Issued when you created your application.
	ClientSecret *string `queryParam:"style=form,explode=true,name=client_secret"`
	// Authentication token. Requires scope: `none`
	Token *string `queryParam:"style=form,explode=true,name=token"`
}

type AppsUninstallResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	AppsUninstallErrorSchema map[string]map[string]interface{}
	// Typical success response
	AppsUninstallSchema map[string]map[string]interface{}
}
