// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AppsPermissionsScopesListSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AppsPermissionsScopesListRequest struct {
	// Authentication token. Requires scope: `none`
	Token string `queryParam:"style=form,explode=true,name=token"`
}

type AppsPermissionsScopesListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical successful paginated response
	APIPermissionsScopesListSuccessSchema map[string]map[string]interface{}
	// Typical error response
	AppsPermissionsScopesListErrorSchema map[string]map[string]interface{}
}
