// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AppsPermissionsRequestSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AppsPermissionsRequestRequest struct {
	// A comma separated list of scopes to request for
	Scopes string `queryParam:"style=form,explode=true,name=scopes"`
	// Authentication token. Requires scope: `none`
	Token string `queryParam:"style=form,explode=true,name=token"`
	// Token used to trigger the permissions API
	TriggerID string `queryParam:"style=form,explode=true,name=trigger_id"`
}

type AppsPermissionsRequestResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Standard failure response when trigger_id is invalid
	AppsPermissionsRequestErrorSchema map[string]map[string]interface{}
	// Standard success response when used with a user token
	AppsPermissionsRequestSchema map[string]map[string]interface{}
}
