// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AuthTestSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AuthTestRequest struct {
	// Authentication token. Requires scope: `none`
	Token string `header:"style=simple,explode=false,name=token"`
}

type AuthTestResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Standard failure response when used with an invalid token
	AuthTestErrorSchema map[string]map[string]interface{}
	// Standard success response when used with a user token
	AuthTestSuccessSchema map[string]map[string]interface{}
}
