// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type BotsInfoSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type BotsInfoRequest struct {
	// Bot user to get info on
	Bot *string `queryParam:"style=form,explode=true,name=bot"`
	// Authentication token. Requires scope: `users:read`
	Token string `queryParam:"style=form,explode=true,name=token"`
}

type BotsInfoResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// When no bot can be found, it returns an error.
	BotsInfoErrorSchema map[string]map[string]interface{}
	// When successful, returns bot info by bot ID.
	BotsInfoSchema map[string]map[string]interface{}
}
