// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CallsEndSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type CallsEndApplicationJSON struct {
	// Call duration in seconds
	Duration *int `json:"duration,omitempty"`
	// `id` returned when registering the call using the [`calls.add`](/methods/calls.add) method.
	ID string `json:"id"`
}

type CallsEndRequest struct {
	RequestBody CallsEndApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `calls:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type CallsEndResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
