// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CallsParticipantsRemoveSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type CallsParticipantsRemoveApplicationJSON struct {
	// `id` returned by the [`calls.add`](/methods/calls.add) method.
	ID string `json:"id"`
	// The list of users to remove as participants in the Call. [Read more on how to specify users here](/apis/calls#users).
	Users string `json:"users"`
}

type CallsParticipantsRemoveRequest struct {
	RequestBody CallsParticipantsRemoveApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `calls:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type CallsParticipantsRemoveResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
