// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CallsInfoSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type CallsInfoRequest struct {
	// `id` of the Call returned by the [`calls.add`](/methods/calls.add) method.
	ID string `queryParam:"style=form,explode=true,name=id"`
	// Authentication token. Requires scope: `calls:read`
	Token string `header:"style=simple,explode=false,name=token"`
}

type CallsInfoResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
