// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CallsAddSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type CallsAddApplicationJSON struct {
	// The valid Slack user ID of the user who created this Call. When this method is called with a user token, the `created_by` field is optional and defaults to the authed user of the token. Otherwise, the field is required.
	CreatedBy *string `json:"created_by,omitempty"`
	// Call start time in UTC UNIX timestamp format
	DateStart *int `json:"date_start,omitempty"`
	// When supplied, available Slack clients will attempt to directly launch the 3rd-party Call with this URL.
	DesktopAppJoinURL *string `json:"desktop_app_join_url,omitempty"`
	// An optional, human-readable ID supplied by the 3rd-party Call provider. If supplied, this ID will be displayed in the Call object.
	ExternalDisplayID *string `json:"external_display_id,omitempty"`
	// An ID supplied by the 3rd-party Call provider. It must be unique across all Calls from that service.
	ExternalUniqueID string `json:"external_unique_id"`
	// The URL required for a client to join the Call.
	JoinURL string `json:"join_url"`
	// The name of the Call.
	Title *string `json:"title,omitempty"`
	// The list of users to register as participants in the Call. [Read more on how to specify users here](/apis/calls#users).
	Users *string `json:"users,omitempty"`
}

type CallsAddRequest struct {
	RequestBody CallsAddApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `calls:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type CallsAddResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
