// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CallsUpdateSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type CallsUpdateApplicationJSON struct {
	// When supplied, available Slack clients will attempt to directly launch the 3rd-party Call with this URL.
	DesktopAppJoinURL *string `json:"desktop_app_join_url,omitempty"`
	// `id` returned by the [`calls.add`](/methods/calls.add) method.
	ID string `json:"id"`
	// The URL required for a client to join the Call.
	JoinURL *string `json:"join_url,omitempty"`
	// The name of the Call.
	Title *string `json:"title,omitempty"`
}

type CallsUpdateRequest struct {
	RequestBody CallsUpdateApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `calls:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type CallsUpdateResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
