// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ChatPostEphemeralSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type ChatPostEphemeralApplicationJSON struct {
	// Pass true to post the message as the authed user. Defaults to true if the chat:write:bot scope is not included. Otherwise, defaults to false.
	AsUser *bool `json:"as_user,omitempty"`
	// A JSON-based array of structured attachments, presented as a URL-encoded string.
	Attachments *string `json:"attachments,omitempty"`
	// A JSON-based array of structured blocks, presented as a URL-encoded string.
	Blocks *string `json:"blocks,omitempty"`
	// Channel, private group, or IM channel to send message to. Can be an encoded ID, or a name.
	Channel string `json:"channel"`
	// Emoji to use as the icon for this message. Overrides `icon_url`. Must be used in conjunction with `as_user` set to `false`, otherwise ignored. See [authorship](#authorship) below.
	IconEmoji *string `json:"icon_emoji,omitempty"`
	// URL to an image to use as the icon for this message. Must be used in conjunction with `as_user` set to false, otherwise ignored. See [authorship](#authorship) below.
	IconURL *string `json:"icon_url,omitempty"`
	// Find and link channel names and usernames.
	LinkNames *bool `json:"link_names,omitempty"`
	// Change how messages are treated. Defaults to `none`. See [below](#formatting).
	Parse *string `json:"parse,omitempty"`
	// How this field works and whether it is required depends on other fields you use in your API call. [See below](#text_usage) for more detail.
	Text *string `json:"text,omitempty"`
	// Provide another message's `ts` value to post this message in a thread. Avoid using a reply's `ts` value; use its parent's value instead. Ephemeral messages in threads are only shown if there is already an active thread.
	ThreadTs *string `json:"thread_ts,omitempty"`
	// `id` of the user who will receive the ephemeral message. The user should be in the channel specified by the `channel` argument.
	User string `json:"user"`
	// Set your bot's user name. Must be used in conjunction with `as_user` set to false, otherwise ignored. See [authorship](#authorship) below.
	Username *string `json:"username,omitempty"`
}

type ChatPostEphemeralRequest struct {
	RequestBody ChatPostEphemeralApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `chat:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type ChatPostEphemeralResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	ChatPostEphemeralErrorSchema map[string]map[string]interface{}
	// Typical success response
	ChatPostEphemeralSuccessSchema map[string]map[string]interface{}
}
