// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ChatMeMessageSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type ChatMeMessageApplicationJSON struct {
	// Channel to send message to. Can be a public channel, private group or IM channel. Can be an encoded ID, or a name.
	Channel *string `json:"channel,omitempty"`
	// Text of the message to send.
	Text *string `json:"text,omitempty"`
}

type ChatMeMessageRequest struct {
	RequestBody *ChatMeMessageApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `chat:write`
	Token *string `header:"style=simple,explode=false,name=token"`
}

type ChatMeMessageResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	ChatMeMessageErrorSchema map[string]map[string]interface{}
	// Typical success response
	ChatMeMessageSchema map[string]map[string]interface{}
}
