// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ConversationsInviteSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type ConversationsInviteApplicationJSON struct {
	// The ID of the public or private channel to invite user(s) to.
	Channel *string `json:"channel,omitempty"`
	// A comma separated list of user IDs. Up to 1000 users may be listed.
	Users *string `json:"users,omitempty"`
}

type ConversationsInviteRequest struct {
	RequestBody *ConversationsInviteApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `conversations:write`
	Token *string `header:"style=simple,explode=false,name=token"`
}

type ConversationsInviteResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical success response when an invitation is extended
	ConversationsInviteErrorSchema map[string]map[string]interface{}
}
