// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ConversationsCloseSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type ConversationsCloseApplicationJSON struct {
	// Conversation to close.
	Channel *string `json:"channel,omitempty"`
}

type ConversationsCloseRequest struct {
	RequestBody *ConversationsCloseApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `conversations:write`
	Token *string `header:"style=simple,explode=false,name=token"`
}

type ConversationsCloseResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	ConversationsCloseErrorSchema map[string]map[string]interface{}
	// Typical success response
	ConversationsCloseSuccessSchema map[string]map[string]interface{}
}
