// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ConversationsArchiveSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type ConversationsArchiveApplicationJSON struct {
	// ID of conversation to archive
	Channel *string `json:"channel,omitempty"`
}

type ConversationsArchiveRequest struct {
	RequestBody *ConversationsArchiveApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `conversations:write`
	Token *string `header:"style=simple,explode=false,name=token"`
}

type ConversationsArchiveResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	ConversationsArchiveErrorSchema map[string]map[string]interface{}
	// Typical success response
	ConversationsArchiveSuccessSchema map[string]map[string]interface{}
}
