// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ConversationsJoinSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type ConversationsJoinApplicationJSON struct {
	// ID of conversation to join
	Channel *string `json:"channel,omitempty"`
}

type ConversationsJoinRequest struct {
	RequestBody *ConversationsJoinApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `channels:write`
	Token *string `header:"style=simple,explode=false,name=token"`
}

type ConversationsJoinResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response if the conversation is archived and cannot be joined
	ConversationsJoinErrorSchema map[string]map[string]interface{}
	// Typical success response
	ConversationsJoinSuccessSchema map[string]map[string]interface{}
}
