// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ConversationsMembersSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type ConversationsMembersRequest struct {
	// ID of the conversation to retrieve members for
	Channel *string `queryParam:"style=form,explode=true,name=channel"`
	// Paginate through collections of data by setting the `cursor` parameter to a `next_cursor` attribute returned by a previous request's `response_metadata`. Default value fetches the first "page" of the collection. See [pagination](/docs/pagination) for more detail.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the users list hasn't been reached.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Authentication token. Requires scope: `conversations:read`
	Token *string `queryParam:"style=form,explode=true,name=token"`
}

type ConversationsMembersResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response when an invalid cursor is provided
	ConversationsMembersErrorSchema map[string]map[string]interface{}
	// Typical paginated success response
	ConversationsMembersSuccessSchema map[string]map[string]interface{}
}
