// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ConversationsMarkSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type ConversationsMarkApplicationJSON struct {
	// Channel or conversation to set the read cursor for.
	Channel *string `json:"channel,omitempty"`
	// Unique identifier of message you want marked as most recently seen in this conversation.
	Ts *float64 `json:"ts,omitempty"`
}

type ConversationsMarkRequest struct {
	RequestBody *ConversationsMarkApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `conversations:write`
	Token *string `header:"style=simple,explode=false,name=token"`
}

type ConversationsMarkResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	ConversationsMarkErrorSchema map[string]map[string]interface{}
	// Typical success response
	ConversationsMarkSuccessSchema map[string]map[string]interface{}
}
