// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DialogOpenSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type DialogOpenRequest struct {
	// The dialog definition. This must be a JSON-encoded string.
	Dialog string `queryParam:"style=form,explode=true,name=dialog"`
	// Authentication token. Requires scope: `none`
	Token string `header:"style=simple,explode=false,name=token"`
	// Exchange a trigger to post to the user.
	TriggerID string `queryParam:"style=form,explode=true,name=trigger_id"`
}

type DialogOpenResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response, before getting to any possible validation errors.
	DialogOpenErrorSchema map[string]map[string]interface{}
	// Typical success response is quite minimal.
	DialogOpenSchema map[string]map[string]interface{}
}
