// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DndEndDndSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type DndEndDndRequest struct {
	// Authentication token. Requires scope: `dnd:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type DndEndDndResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	DndEndDndErrorSchema map[string]map[string]interface{}
	// Typical success response
	DndEndDndSchema map[string]map[string]interface{}
}
