// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DndEndSnoozeSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type DndEndSnoozeRequest struct {
	// Authentication token. Requires scope: `dnd:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type DndEndSnoozeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	DndEndSnoozeErrorSchema map[string]map[string]interface{}
	// Typical success response
	DndEndSnoozeSchema map[string]map[string]interface{}
}
