// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DndTeamInfoSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type DndTeamInfoRequest struct {
	// Authentication token. Requires scope: `dnd:read`
	Token *string `queryParam:"style=form,explode=true,name=token"`
	// Comma-separated list of users to fetch Do Not Disturb status for
	Users *string `queryParam:"style=form,explode=true,name=users"`
}

type DndTeamInfoResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
