// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type EmojiListSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type EmojiListRequest struct {
	// Authentication token. Requires scope: `emoji:read`
	Token string `queryParam:"style=form,explode=true,name=token"`
}

type EmojiListResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
