// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type FilesListSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type FilesListRequest struct {
	// Filter files appearing in a specific channel, indicated by its ID.
	Channel *string `queryParam:"style=form,explode=true,name=channel"`
	Count   *string `queryParam:"style=form,explode=true,name=count"`
	Page    *string `queryParam:"style=form,explode=true,name=page"`
	// Show truncated file info for files hidden due to being too old, and the team who owns the file being over the file limit.
	ShowFilesHiddenByLimit *bool `queryParam:"style=form,explode=true,name=show_files_hidden_by_limit"`
	// Authentication token. Requires scope: `files:read`
	Token *string `queryParam:"style=form,explode=true,name=token"`
	// Filter files created after this timestamp (inclusive).
	TsFrom *float64 `queryParam:"style=form,explode=true,name=ts_from"`
	// Filter files created before this timestamp (inclusive).
	TsTo *float64 `queryParam:"style=form,explode=true,name=ts_to"`
	// Filter files by type ([see below](#file_types)). You can pass multiple values in the types argument, like `types=spaces,snippets`.The default value is `all`, which does not filter the list.
	Types *string `queryParam:"style=form,explode=true,name=types"`
	// Filter files created by a single user.
	User *string `queryParam:"style=form,explode=true,name=user"`
}

type FilesListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	FilesListErrorSchema map[string]map[string]interface{}
	// Typical success response
	FilesListSchema map[string]map[string]interface{}
}
