// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type FilesRevokePublicURLSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type FilesRevokePublicURLApplicationJSON struct {
	// File to revoke
	File *string `json:"file,omitempty"`
}

type FilesRevokePublicURLRequest struct {
	RequestBody *FilesRevokePublicURLApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `files:write:user`
	Token *string `header:"style=simple,explode=false,name=token"`
}

type FilesRevokePublicURLResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	FilesRevokePublicURLErrorSchema map[string]map[string]interface{}
	// Typical success response
	FilesRevokePublicURLSchema map[string]map[string]interface{}
}
