// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type FilesRemoteInfoSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type FilesRemoteInfoRequest struct {
	// Creator defined GUID for the file.
	ExternalID *string `queryParam:"style=form,explode=true,name=external_id"`
	// Specify a file by providing its ID.
	File *string `queryParam:"style=form,explode=true,name=file"`
	// Authentication token. Requires scope: `remote_files:read`
	Token *string `queryParam:"style=form,explode=true,name=token"`
}

type FilesRemoteInfoResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
