// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type FilesSharedPublicURLSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type FilesSharedPublicURLApplicationJSON struct {
	// File to share
	File *string `json:"file,omitempty"`
}

type FilesSharedPublicURLRequest struct {
	RequestBody *FilesSharedPublicURLApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `files:write:user`
	Token *string `header:"style=simple,explode=false,name=token"`
}

type FilesSharedPublicURLResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	FilesSharedPublicURLErrorSchema map[string]map[string]interface{}
	// Typical success response
	FilesSharedPublicURLSchema map[string]map[string]interface{}
}
