// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type FilesDeleteSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type FilesDeleteApplicationJSON struct {
	// ID of file to delete.
	File *string `json:"file,omitempty"`
}

type FilesDeleteRequest struct {
	RequestBody *FilesDeleteApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `files:write:user`
	Token *string `header:"style=simple,explode=false,name=token"`
}

type FilesDeleteResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	FilesDeleteErrorSchema map[string]map[string]interface{}
	// Typical success response
	FilesDeleteSchema map[string]map[string]interface{}
}
