// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type FilesRemoteShareSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type FilesRemoteShareRequest struct {
	// Comma-separated list of channel IDs where the file will be shared.
	Channels *string `queryParam:"style=form,explode=true,name=channels"`
	// The globally unique identifier (GUID) for the file, as set by the app registering the file with Slack.  Either this field or `file` or both are required.
	ExternalID *string `queryParam:"style=form,explode=true,name=external_id"`
	// Specify a file registered with Slack by providing its ID. Either this field or `external_id` or both are required.
	File *string `queryParam:"style=form,explode=true,name=file"`
	// Authentication token. Requires scope: `remote_files:share`
	Token *string `queryParam:"style=form,explode=true,name=token"`
}

type FilesRemoteShareResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
