// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type FilesRemoteAddSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type FilesRemoteAddRequestBody struct {
	// Creator defined GUID for the file.
	ExternalID *string `form:"name=external_id"`
	// URL of the remote file.
	ExternalURL *string `form:"name=external_url"`
	// type of file
	Filetype *string `form:"name=filetype"`
	// A text file (txt, pdf, doc, etc.) containing textual search terms that are used to improve discovery of the remote file.
	IndexableFileContents *string `form:"name=indexable_file_contents"`
	// Preview of the document via `multipart/form-data`.
	PreviewImage *string `form:"name=preview_image"`
	// Title of the file being shared.
	Title *string `form:"name=title"`
	// Authentication token. Requires scope: `remote_files:write`
	Token *string `form:"name=token"`
}

type FilesRemoteAddResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
