// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type OauthV2AccessSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type OauthV2AccessRequest struct {
	// Issued when you created your application.
	ClientID *string `queryParam:"style=form,explode=true,name=client_id"`
	// Issued when you created your application.
	ClientSecret *string `queryParam:"style=form,explode=true,name=client_secret"`
	// The `code` param returned via the OAuth callback.
	Code string `queryParam:"style=form,explode=true,name=code"`
	// This must match the originally submitted URI (if one was sent).
	RedirectURI *string `queryParam:"style=form,explode=true,name=redirect_uri"`
}

type OauthV2AccessResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Successful token request with scopes for both a bot user and a user token
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
