// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type OauthAccessSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type OauthAccessRequest struct {
	// Issued when you created your application.
	ClientID *string `queryParam:"style=form,explode=true,name=client_id"`
	// Issued when you created your application.
	ClientSecret *string `queryParam:"style=form,explode=true,name=client_secret"`
	// The `code` param returned via the OAuth callback.
	Code *string `queryParam:"style=form,explode=true,name=code"`
	// This must match the originally submitted URI (if one was sent).
	RedirectURI *string `queryParam:"style=form,explode=true,name=redirect_uri"`
	// Request the user to add your app only to a single channel. Only valid with a [legacy workspace app](https://api.slack.com/legacy-workspace-apps).
	SingleChannel *bool `queryParam:"style=form,explode=true,name=single_channel"`
}

type OauthAccessResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Successful user token negotiation for a single scope
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
