// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PinsRemoveSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type PinsRemoveApplicationJSON struct {
	// Channel where the item is pinned to.
	Channel string `json:"channel"`
	// Timestamp of the message to un-pin.
	Timestamp *string `json:"timestamp,omitempty"`
}

type PinsRemoveRequest struct {
	RequestBody PinsRemoveApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `pins:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type PinsRemoveResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	PinsRemoveErrorSchema map[string]map[string]interface{}
	// Typical success response
	PinsRemoveSchema map[string]map[string]interface{}
}
