// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PinsAddSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type PinsAddApplicationJSON struct {
	// Channel to pin the item in.
	Channel string `json:"channel"`
	// Timestamp of the message to pin.
	Timestamp *string `json:"timestamp,omitempty"`
}

type PinsAddRequest struct {
	RequestBody PinsAddApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `pins:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type PinsAddResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	PinsAddErrorSchema map[string]map[string]interface{}
	// Typical success response
	PinsAddSchema map[string]map[string]interface{}
}
