// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PinsListSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type PinsListRequest struct {
	// Channel to get pinned items for.
	Channel string `queryParam:"style=form,explode=true,name=channel"`
	// Authentication token. Requires scope: `pins:read`
	Token string `queryParam:"style=form,explode=true,name=token"`
}

type PinsListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	PinsListErrorSchema map[string]map[string]interface{}
	// Typical success response
	PinsListSuccessSchema map[string]interface{}
}
