// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ReactionsRemoveSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type ReactionsRemoveApplicationJSON struct {
	// Channel where the message to remove reaction from was posted.
	Channel *string `json:"channel,omitempty"`
	// File to remove reaction from.
	File *string `json:"file,omitempty"`
	// File comment to remove reaction from.
	FileComment *string `json:"file_comment,omitempty"`
	// Reaction (emoji) name.
	Name string `json:"name"`
	// Timestamp of the message to remove reaction from.
	Timestamp *string `json:"timestamp,omitempty"`
}

type ReactionsRemoveRequest struct {
	RequestBody ReactionsRemoveApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `reactions:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type ReactionsRemoveResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	ReactionsRemoveErrorSchema map[string]map[string]interface{}
	// Typical success response
	ReactionsRemoveSchema map[string]map[string]interface{}
}
