// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ReactionsAddSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type ReactionsAddApplicationJSON struct {
	// Channel where the message to add reaction to was posted.
	Channel string `json:"channel"`
	// Reaction (emoji) name.
	Name string `json:"name"`
	// Timestamp of the message to add reaction to.
	Timestamp string `json:"timestamp"`
}

type ReactionsAddRequest struct {
	RequestBody ReactionsAddApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `reactions:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type ReactionsAddResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	ReactionsAddErrorSchema map[string]map[string]interface{}
	// Typical success response
	ReactionsAddSchema map[string]map[string]interface{}
}
