// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RemindersCompleteSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type RemindersCompleteApplicationJSON struct {
	// The ID of the reminder to be marked as complete
	Reminder *string `json:"reminder,omitempty"`
}

type RemindersCompleteRequest struct {
	RequestBody *RemindersCompleteApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `reminders:write`
	Token *string `header:"style=simple,explode=false,name=token"`
}

type RemindersCompleteResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	RemindersCompleteErrorSchema map[string]map[string]interface{}
	// Typical success response
	RemindersCompleteSchema map[string]map[string]interface{}
}
