// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RemindersListSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type RemindersListRequest struct {
	// Authentication token. Requires scope: `reminders:read`
	Token *string `queryParam:"style=form,explode=true,name=token"`
}

type RemindersListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	RemindersListErrorSchema map[string]map[string]interface{}
	// Typical success response
	RemindersListSchema map[string]map[string]interface{}
}
