// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RemindersAddSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type RemindersAddApplicationJSON struct {
	// The content of the reminder
	Text string `json:"text"`
	// When this reminder should happen: the Unix timestamp (up to five years from now), the number of seconds until the reminder (if within 24 hours), or a natural language description (Ex. "in 15 minutes," or "every Thursday")
	Time string `json:"time"`
	// The user who will receive the reminder. If no user is specified, the reminder will go to user who created it.
	User *string `json:"user,omitempty"`
}

type RemindersAddRequest struct {
	RequestBody RemindersAddApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `reminders:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type RemindersAddResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	RemindersAddErrorSchema map[string]map[string]interface{}
	// Typical success response
	RemindersAddSchema map[string]map[string]interface{}
}
