// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RtmConnectSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type RtmConnectRequest struct {
	// Batch presence deliveries via subscription. Enabling changes the shape of `presence_change` events. See [batch presence](/docs/presence-and-status#batching).
	BatchPresenceAware *bool `queryParam:"style=form,explode=true,name=batch_presence_aware"`
	// Only deliver presence events when requested by subscription. See [presence subscriptions](/docs/presence-and-status#subscriptions).
	PresenceSub *bool `queryParam:"style=form,explode=true,name=presence_sub"`
	// Authentication token. Requires scope: `rtm:stream`
	Token string `queryParam:"style=form,explode=true,name=token"`
}

type RtmConnectResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	RtmConnectErrorSchema map[string]map[string]interface{}
	// Typical success response
	RtmConnectSchema map[string]map[string]interface{}
}
