// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type StarsAddSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type StarsAddApplicationJSON struct {
	// Channel to add star to, or channel where the message to add star to was posted (used with `timestamp`).
	Channel *string `json:"channel,omitempty"`
	// File to add star to.
	File *string `json:"file,omitempty"`
	// File comment to add star to.
	FileComment *string `json:"file_comment,omitempty"`
	// Timestamp of the message to add star to.
	Timestamp *string `json:"timestamp,omitempty"`
}

type StarsAddRequest struct {
	RequestBody *StarsAddApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `stars:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type StarsAddResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	StarsAddErrorSchema map[string]map[string]interface{}
	// Typical success response
	StarsAddSchema map[string]map[string]interface{}
}
