// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type StarsRemoveSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type StarsRemoveApplicationJSON struct {
	// Channel to remove star from, or channel where the message to remove star from was posted (used with `timestamp`).
	Channel *string `json:"channel,omitempty"`
	// File to remove star from.
	File *string `json:"file,omitempty"`
	// File comment to remove star from.
	FileComment *string `json:"file_comment,omitempty"`
	// Timestamp of the message to remove star from.
	Timestamp *string `json:"timestamp,omitempty"`
}

type StarsRemoveRequest struct {
	RequestBody *StarsRemoveApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `stars:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type StarsRemoveResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	StarsRemoveErrorSchema map[string]map[string]interface{}
	// Typical success response
	StarsRemoveSchema map[string]map[string]interface{}
}
