// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type TeamProfileGetSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type TeamProfileGetRequest struct {
	// Authentication token. Requires scope: `users.profile:read`
	Token string `queryParam:"style=form,explode=true,name=token"`
	// Filter by visibility.
	Visibility *string `queryParam:"style=form,explode=true,name=visibility"`
}

type TeamProfileGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	TeamProfileGetErrorSchema map[string]map[string]interface{}
	// Typical success response
	TeamProfileGetSuccessSchema map[string]map[string]interface{}
}
