// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type TeamBillableInfoSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type TeamBillableInfoRequest struct {
	// Authentication token. Requires scope: `admin`
	Token string `queryParam:"style=form,explode=true,name=token"`
	// A user to retrieve the billable information for. Defaults to all users.
	User *string `queryParam:"style=form,explode=true,name=user"`
}

type TeamBillableInfoResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
