// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UsersGetPresenceSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type UsersGetPresenceRequest struct {
	// Authentication token. Requires scope: `users:read`
	Token string `queryParam:"style=form,explode=true,name=token"`
	// User to get presence info on. Defaults to the authed user.
	User *string `queryParam:"style=form,explode=true,name=user"`
}

type UsersGetPresenceResponse struct {
	// When requesting information for a different user, this method just returns the current presence (either `active` or `away`).
	APIMethodUsersGetPresence map[string]map[string]interface{}
	ContentType               string
	StatusCode                int
	RawResponse               *http.Response
	// Typical error response
	UsersCountsErrorSchema map[string]map[string]interface{}
}
