// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UsergroupsListSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type UsergroupsListRequest struct {
	// Include the number of users in each User Group.
	IncludeCount *bool `queryParam:"style=form,explode=true,name=include_count"`
	// Include disabled User Groups.
	IncludeDisabled *bool `queryParam:"style=form,explode=true,name=include_disabled"`
	// Include the list of users for each User Group.
	IncludeUsers *bool `queryParam:"style=form,explode=true,name=include_users"`
	// Authentication token. Requires scope: `usergroups:read`
	Token string `queryParam:"style=form,explode=true,name=token"`
}

type UsergroupsListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	UsergroupsListErrorSchema map[string]map[string]interface{}
	// Typical success response
	UsergroupsListSchema map[string]map[string]interface{}
}
