// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UsergroupsUsersListSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type UsergroupsUsersListRequest struct {
	// Allow results that involve disabled User Groups.
	IncludeDisabled *bool `queryParam:"style=form,explode=true,name=include_disabled"`
	// Authentication token. Requires scope: `usergroups:read`
	Token string `queryParam:"style=form,explode=true,name=token"`
	// The encoded ID of the User Group to update.
	Usergroup string `queryParam:"style=form,explode=true,name=usergroup"`
}

type UsergroupsUsersListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Standard failure response when used with an invalid token
	UsergroupsUsersListErrorSchema map[string]map[string]interface{}
	// Standard success response when used with a user token
	UsergroupsUsersListSchema map[string]map[string]interface{}
}
