// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UsersProfileGetSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type UsersProfileGetRequest struct {
	// Include labels for each ID in custom profile fields
	IncludeLabels *bool `queryParam:"style=form,explode=true,name=include_labels"`
	// Authentication token. Requires scope: `users.profile:read`
	Token string `queryParam:"style=form,explode=true,name=token"`
	// User to retrieve profile info for
	User *string `queryParam:"style=form,explode=true,name=user"`
}

type UsersProfileGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	UsersProfileGetErrorSchema map[string]map[string]interface{}
	// Typical success response
	UsersProfileGetSchema map[string]map[string]interface{}
}
