// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UsersSetActiveSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type UsersSetActiveRequest struct {
	// Authentication token. Requires scope: `users:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type UsersSetActiveResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	UsersSetActiveErrorSchema map[string]map[string]interface{}
	// Typical success response
	UsersSetActiveSchema map[string]map[string]interface{}
}
