// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UsersDeletePhotoSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type UsersDeletePhotoRequestBody struct {
	// Authentication token. Requires scope: `users.profile:write`
	Token string `form:"name=token"`
}

type UsersDeletePhotoResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	UsersDeletePhotoErrorSchema map[string]map[string]interface{}
	// Typical success response
	UsersDeletePhotoSchema map[string]map[string]interface{}
}
