// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UsergroupsDisableSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type UsergroupsDisableApplicationJSON struct {
	// Include the number of users in the User Group.
	IncludeCount *bool `json:"include_count,omitempty"`
	// The encoded ID of the User Group to disable.
	Usergroup string `json:"usergroup"`
}

type UsergroupsDisableRequest struct {
	RequestBody UsergroupsDisableApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `usergroups:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type UsergroupsDisableResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	UsergroupsDisableErrorSchema map[string]map[string]interface{}
	// Typical success response
	UsergroupsDisableSchema map[string]map[string]interface{}
}
