// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UsergroupsEnableSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type UsergroupsEnableApplicationJSON struct {
	// Include the number of users in the User Group.
	IncludeCount *bool `json:"include_count,omitempty"`
	// The encoded ID of the User Group to enable.
	Usergroup string `json:"usergroup"`
}

type UsergroupsEnableRequest struct {
	RequestBody UsergroupsEnableApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `usergroups:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type UsergroupsEnableResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	UsergroupsEnableErrorSchema map[string]map[string]interface{}
	// Typical success response
	UsergroupsEnableSchema map[string]map[string]interface{}
}
