// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UsersSetPresenceSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type UsersSetPresenceApplicationJSON struct {
	// Either `auto` or `away`
	Presence string `json:"presence"`
}

type UsersSetPresenceRequest struct {
	RequestBody UsersSetPresenceApplicationJSON `request:"mediaType=application/json"`
	// Authentication token. Requires scope: `users:write`
	Token string `header:"style=simple,explode=false,name=token"`
}

type UsersSetPresenceResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Typical error response
	UsersSetPresenceErrorSchema map[string]map[string]interface{}
	// Typical success response
	UsersSetPresenceSchema map[string]map[string]interface{}
}
