// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ViewsPushSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type ViewsPushRequest struct {
	// Authentication token. Requires scope: `none`
	Token string `header:"style=simple,explode=false,name=token"`
	// Exchange a trigger to post to the user.
	TriggerID string `queryParam:"style=form,explode=true,name=trigger_id"`
	// A [view payload](/reference/surfaces/views). This must be a JSON-encoded string.
	View string `queryParam:"style=form,explode=true,name=view"`
}

type ViewsPushResponse struct {
	ContentType string
	// Typical error response.
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response includes the pushed view payload.
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
