// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type WorkflowsUpdateStepSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type WorkflowsUpdateStepRequest struct {
	// A JSON key-value map of inputs required from a user during configuration. This is the data your app expects to receive when the workflow step starts. **Please note**: the embedded variable format is set and replaced by the workflow system. You cannot create custom variables that will be replaced at runtime. [Read more about variables in workflow steps here](/workflows/steps#variables).
	Inputs *string `queryParam:"style=form,explode=true,name=inputs"`
	// An JSON array of output objects used during step execution. This is the data your app agrees to provide when your workflow step was executed.
	Outputs *string `queryParam:"style=form,explode=true,name=outputs"`
	// An optional field that can be used to override app image that is shown in the Workflow Builder.
	StepImageURL *string `queryParam:"style=form,explode=true,name=step_image_url"`
	// An optional field that can be used to override the step name that is shown in the Workflow Builder.
	StepName *string `queryParam:"style=form,explode=true,name=step_name"`
	// Authentication token. Requires scope: `workflow.steps:execute`
	Token string `header:"style=simple,explode=false,name=token"`
	// A context identifier provided with `view_submission` payloads used to call back to `workflows.updateStep`.
	WorkflowStepEditID string `queryParam:"style=form,explode=true,name=workflow_step_edit_id"`
}

type WorkflowsUpdateStepResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
