// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type WorkflowsStepCompletedSecurity struct {
	SlackAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type WorkflowsStepCompletedRequest struct {
	// Key-value object of outputs from your step. Keys of this object reflect the configured `key` properties of your [`outputs`](/reference/workflows/workflow_step#output) array from your `workflow_step` object.
	Outputs *string `queryParam:"style=form,explode=true,name=outputs"`
	// Authentication token. Requires scope: `workflow.steps:execute`
	Token string `header:"style=simple,explode=false,name=token"`
	// Context identifier that maps to the correct workflow step execution.
	WorkflowStepExecuteID string `queryParam:"style=form,explode=true,name=workflow_step_execute_id"`
}

type WorkflowsStepCompletedResponse struct {
	ContentType string
	// Typical error response
	DefaultErrorTemplate map[string]map[string]interface{}
	// Typical success response
	DefaultSuccessTemplate map[string]map[string]interface{}
	StatusCode             int
	RawResponse            *http.Response
}
